# Generated by Django 5.1.1 on 2024-10-07 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.IntegerField()),
                ('books', models.ManyToManyField(to='shop.book')),
                ('embroideries', models.ManyToManyField(to='shop.embroidery')),
            ],
        ),
    ]
